/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as InstancesIndexRouteImport } from "./routes/instances/index"
import { Route as InstancesNewRouteImport } from "./routes/instances/new"
import { Route as InstancesFidRouteImport } from "./routes/instances/$fid"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: "/instances/",
  path: "/instances/",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesNewRoute = InstancesNewRouteImport.update({
  id: "/instances/new",
  path: "/instances/new",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesFidRoute = InstancesFidRouteImport.update({
  id: "/instances/$fid",
  path: "/instances/$fid",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/instances/$fid": typeof InstancesFidRoute
  "/instances/new": typeof InstancesNewRoute
  "/instances/": typeof InstancesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/instances/$fid": typeof InstancesFidRoute
  "/instances/new": typeof InstancesNewRoute
  "/instances": typeof InstancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/instances/$fid": typeof InstancesFidRoute
  "/instances/new": typeof InstancesNewRoute
  "/instances/": typeof InstancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/instances/$fid"
    | "/instances/new"
    | "/instances/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/settings" | "/instances/$fid" | "/instances/new" | "/instances"
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/instances/$fid"
    | "/instances/new"
    | "/instances/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  InstancesFidRoute: typeof InstancesFidRoute
  InstancesNewRoute: typeof InstancesNewRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/": {
      id: "/instances/"
      path: "/instances"
      fullPath: "/instances/"
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/new": {
      id: "/instances/new"
      path: "/instances/new"
      fullPath: "/instances/new"
      preLoaderRoute: typeof InstancesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances/$fid": {
      id: "/instances/$fid"
      path: "/instances/$fid"
      fullPath: "/instances/$fid"
      preLoaderRoute: typeof InstancesFidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  InstancesFidRoute: InstancesFidRoute,
  InstancesNewRoute: InstancesNewRoute,
  InstancesIndexRoute: InstancesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
